// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PhishGuard.Backend.Data;

#nullable disable

namespace PhishGuard.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260805181159_AddDashboardOverviewIndex")]
    partial class AddDashboardOverviewIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CampaignTarget", b =>
                {
                    b.Property<Guid>("CampaignsId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaigns_id");

                    b.Property<Guid>("TargetsId")
                        .HasColumnType("uuid")
                        .HasColumnName("targets_id");

                    b.HasKey("CampaignsId", "TargetsId")
                        .HasName("pk_campaign_target");

                    b.HasIndex("TargetsId")
                        .HasDatabaseName("ix_campaign_target_targets_id");

                    b.ToTable("campaign_target");
                });

            modelBuilder.Entity("PhishGuard.Backend.Models.Administrador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AcessoFalhasContador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("acesso_falhas_contador");

                    b.Property<DateTime?>("BloqueioFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bloqueio_fim");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_administradores");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_administradores_email");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_administradores_tenant_id");

                    b.ToTable("administradores");
                });

            modelBuilder.Entity("PhishGuard.Backend.Models.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<Guid>("EducationalPageId")
                        .HasColumnType("uuid")
                        .HasColumnName("educational_page_id");

                    b.Property<Guid>("EmailTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("email_template_id");

                    b.Property<Guid>("LandingPageId")
                        .HasColumnType("uuid")
                        .HasColumnName("landing_page_id");

                    b.Property<string>("NomeCampanha")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome_campanha");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_campaigns");

                    b.HasIndex("EducationalPageId")
                        .HasDatabaseName("ix_campaigns_educational_page_id");

                    b.HasIndex("EmailTemplateId")
                        .HasDatabaseName("ix_campaigns_email_template_id");

                    b.HasIndex("LandingPageId")
                        .HasDatabaseName("ix_campaigns_landing_page_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_campaigns_tenant_id");

                    b.ToTable("campaigns", (string)null);
                });

            modelBuilder.Entity("PhishGuard.Backend.Models.EducationalPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("HtmlEducacional")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("html_educacional");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_educational_pages");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_educational_pages_tenant_id");

                    b.ToTable("educational_pages", (string)null);
                });

            modelBuilder.Entity("PhishGuard.Backend.Models.PhishingPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("HtmlCaptura")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("html_captura");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_phishing_pages");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_phishing_pages_tenant_id");

                    b.ToTable("phishing_pages", (string)null);
                });

            modelBuilder.Entity("PhishGuard.Backend.Models.SimulationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("acao");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora");

                    b.Property<string>("IpOrigem")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_origem");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_simulations_logs");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_simulations_logs_campaign_id");

                    b.HasIndex("TargetId")
                        .HasDatabaseName("ix_simulations_logs_target_id");

                    b.HasIndex("TenantId", "DataHora", "Acao", "CampaignId", "TargetId")
                        .HasDatabaseName("ix_simulations_logs_dashboard_overview");

                    b.ToTable("simulations_logs");
                });

            modelBuilder.Entity("PhishGuard.Backend.Models.SmtpConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("host");

                    b.Property<int>("Porta")
                        .HasColumnType("integer")
                        .HasColumnName("porta");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("senha");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("usuario");

                    b.HasKey("Id")
                        .HasName("pk_smtp_configs");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_smtp_configs_tenant_id");

                    b.ToTable("smtp_configs", (string)null);
                });

            modelBuilder.Entity("PhishGuard.Backend.Models.Target", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("departamento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_alvos");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_alvos_tenant_id");

                    b.ToTable("alvos", (string)null);
                });

            modelBuilder.Entity("PhishGuard.Backend.Models.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("assunto");

                    b.Property<string>("CorpoHtml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("corpo_html");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("RemetenteEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("remetente_email");

                    b.Property<string>("RemetenteNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("remetente_nome");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_templates");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_templates_tenant_id");

                    b.ToTable("templates", (string)null);
                });

            modelBuilder.Entity("PhishGuard.Backend.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome_empresa");

                    b.Property<int>("Plano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("plano");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_cnpj");

                    b.ToTable("tenants");
                });

            modelBuilder.Entity("CampaignTarget", b =>
                {
                    b.HasOne("PhishGuard.Backend.Models.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_target_campaigns_campaigns_id");

                    b.HasOne("PhishGuard.Backend.Models.Target", null)
                        .WithMany()
                        .HasForeignKey("TargetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_target_alvos_targets_id");
                });

            modelBuilder.Entity("PhishGuard.Backend.Models.Administrador", b =>
                {
                    b.HasOne("PhishGuard.Backend.Models.Tenant", null)
                        .WithMany("Administradores")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_administradores_tenants_tenant_id");
                });

            modelBuilder.Entity("PhishGuard.Backend.Models.Campaign", b =>
                {
                    b.HasOne("PhishGuard.Backend.Models.EducationalPage", "EducationalPage")
                        .WithMany()
                        .HasForeignKey("EducationalPageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_campaigns_educational_pages_educational_page_id");

                    b.HasOne("PhishGuard.Backend.Models.Template", "Template")
                        .WithMany()
                        .HasForeignKey("EmailTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_campaigns_templates_email_template_id");

                    b.HasOne("PhishGuard.Backend.Models.PhishingPage", "PhishingPage")
                        .WithMany()
                        .HasForeignKey("LandingPageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_campaigns_phishing_pages_landing_page_id");

                    b.HasOne("PhishGuard.Backend.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaigns_tenants_tenant_id");

                    b.Navigation("EducationalPage");

                    b.Navigation("PhishingPage");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("PhishGuard.Backend.Models.EducationalPage", b =>
                {
                    b.HasOne("PhishGuard.Backend.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_educational_pages_tenants_tenant_id");
                });

            modelBuilder.Entity("PhishGuard.Backend.Models.PhishingPage", b =>
                {
                    b.HasOne("PhishGuard.Backend.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_phishing_pages_tenants_tenant_id");
                });

            modelBuilder.Entity("PhishGuard.Backend.Models.SimulationLog", b =>
                {
                    b.HasOne("PhishGuard.Backend.Models.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_simulations_logs_campaigns_campaign_id");

                    b.HasOne("PhishGuard.Backend.Models.Target", null)
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_simulations_logs_alvos_target_id");

                    b.HasOne("PhishGuard.Backend.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_simulations_logs_tenants_tenant_id");
                });

            modelBuilder.Entity("PhishGuard.Backend.Models.SmtpConfig", b =>
                {
                    b.HasOne("PhishGuard.Backend.Models.Tenant", "Tenant")
                        .WithOne("SmtpConfig")
                        .HasForeignKey("PhishGuard.Backend.Models.SmtpConfig", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_smtp_configs_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PhishGuard.Backend.Models.Target", b =>
                {
                    b.HasOne("PhishGuard.Backend.Models.Tenant", null)
                        .WithMany("Alvos")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_alvos_tenants_tenant_id");
                });

            modelBuilder.Entity("PhishGuard.Backend.Models.Template", b =>
                {
                    b.HasOne("PhishGuard.Backend.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_templates_tenants_tenant_id");
                });

            modelBuilder.Entity("PhishGuard.Backend.Models.Tenant", b =>
                {
                    b.Navigation("Administradores");

                    b.Navigation("Alvos");

                    b.Navigation("SmtpConfig");
                });
#pragma warning restore 612, 618
        }
    }
}
